name: mobile_engineer_test
description: An off-site test for the Flutter Mobile Engineer position at Lukky

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images
    - assets/datasets

  fonts:
    - family: Arbutus Slab
      fonts:
        - asset: assets/fonts/ArbutusSlab-Regular.ttf
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
